apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisparr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisparr
  template:
    metadata:
      labels:
        app: whisparr
    spec:
      containers:
      - name: whisparr
        image: ghcr.io/thespad/whisparr:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Istanbul"
        ports:
        - containerPort: 6969
        volumeMounts:
        - name: config-vol
          mountPath: /config
          subPath: whisparr          # config-pvc (SSD) içindeki whisparr klasörü
        - name: config-vol
          mountPath: /downloads
          subPath: downloads         # qBittorrent'in indirdiklerini okumak için SSD
        - name: data-vol
          mountPath: /data
          subPath: media_data        # storage-pvc (GDrive) içindeki ana medya yolu
      volumes:
      - name: config-vol
        persistentVolumeClaim:
          claimName: config-pvc      # Beyin: Ayarlar, DB ve geçici indirmeler (SSD)
      - name: data-vol
        persistentVolumeClaim:
          claimName: storage-pvc     # Kas: Devasa arşiv (GDrive)
