apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-configs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-config-storage
  local:
    path: /mnt/app_configs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - jelly-lab-control-plane
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-config-storage
  resources:
    requests:
      storage: 50Gi
