apiVersion: apps/v1
kind: Deployment
metadata:
  name: tor-proxy
  namespace: default # Kendi namespace'ini yazmayı unutma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tor-proxy
  template:
    metadata:
      labels:
        app: tor-proxy
    spec:
      containers:
      - name: tor
        image: dperson/torproxy
        ports:
        - containerPort: 9050
