apiVersion: apps/v1
kind: Deployment
metadata:
  name: subgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subgen
  template:
    metadata:
      labels:
        app: subgen
    spec:
      containers:
      - name: subgen-container
        image: mccloud/subgen:cpu  # CUDA kütüphanesiz, hafif CPU imajı
        ports:
        - containerPort: 9000
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"

        # --- SAAT AYARI ---
        - name: TZ
          value: "Europe/Istanbul"

        # --- İŞ YÜKÜ VE İŞLEMCİ GÜCÜ ---
        - name: CONCURRENT_TRANSCRIPTIONS
          value: "1"
        - name: WHISPER_THREADS
          value: "4"  # CPU Limiti ile uyumlu 4 thread

        # --- YERELDE DİNLEME VE ÇIKTI ---
        - name: WHISPER_MODEL
          value: "base"
        - name: TRANSCRIBE_DEVICE
          value: "cpu"
        - name: WHISPER_VAD_FILTER
          value: "True"   # Sessizlikleri atla
        - name: WHISPER_BEAM_SIZE
          value: "3"      # Daha az düşün, daha hızlı yaz
        - name: TRANSCRIBE_OR_TRANSLATE
          value: "transcribe"
        - name: APPEND_LANGUAGE_TO_FILENAME
          value: "True"

        # --- HUGGING FACE KİMLİK DOĞRULAMASI ---
        - name: HF_TOKEN
          value: "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"

        # --- ATLANACAK DURUMLAR (HERHANGİ BİR ALTYAZI VARSA ATLA) ---
        - name: SKIP_IF_EXTERNAL_SUBTITLES_EXIST
          value: "True"

        # --- JELLYFIN BAĞLANTI ---
        - name: JELLYFIN_SERVER
          value: "http://jellyfin-service:8096/jellyfin"
        - name: JELLYFIN_TOKEN
          value: "6c1bed94f67940e7ab669c1081a49631"

        resources:
          limits:
            cpu: "4"       # Üst sınır 4 çekirdek
            memory: "6Gi"  # RAM sınırı 6GB
          requests:
            cpu: "2"       # Minimum garanti edilen
            memory: "4Gi"
        volumeMounts:
        - name: media-storage
          mountPath: /data/media
          subPath: media_data/library
      volumes:
      - name: media-storage
        persistentVolumeClaim:
          claimName: storage-pvc
