apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: linuxserver/radarr:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Istanbul"
        ports:
        - containerPort: 7878
        volumeMounts:
        - name: config-vol
          mountPath: /config
          subPath: radarr          # Ayarlar SSD'de
        - name: config-vol
          mountPath: /downloads
          subPath: downloads       # qBittorrent'in indirdiklerini okumak için SSD'ye bakar
        - name: data-vol
          mountPath: /data
          subPath: media_data      # Kendi kütüphanesi Google Drive'da
      volumes:
      - name: config-vol
        persistentVolumeClaim:
          claimName: config-pvc    # SSD (Okuma noktası)
      - name: data-vol
        persistentVolumeClaim:
          claimName: storage-pvc   # GDrive (Yazma noktası)
